hidePatterns: true
# Enable sounds? If you use Spigot 1.8 please set this to false
soundEnable: true
# Enable or disable per banner permission for players.
# If true players need to have "headbanner.<bannerUniquedName>" to access banner.
perBannerPermission: true
lang:
  prefix: '&3&lH&b&lead&3&lB&b&lanner &6» &7'
  notPlayer: '&cYou have to be a player to use that command!'
  page: '(Page %page%/%pages%)'
  guiName: '&9» &0HeadBanner GUI'
  nextPage: '&c&m---&r&c>'
  prevPage: '&c<&c&m--&r&c-'
  bannerRemoved: '&aBanner has been successfully removed from Your head!'
  dontHaveBanner: '&cYou dont have banner on Your helmet slot!'
  removeHatFirst: '&cYou have too take of Your current helmet to set banner!'
  bannerSet: '&aNew banner has been set!'
  dontHavePerm: '&cYou dont have permission to this command!'
  dontHavePermForBannerSet: '&cThis player does not have permissions for this banner!'
  dontHavePermForBanner: '&cYou dont have permission for this banner!'
  configReloaded: '&aConfiguration file has been reloaded!'
  missingArgs: '&cYou have to use correctly format of command!'
  toManyArgs: '&cYou have to use to many args in command!'
  notOnline: '&cThis player is not online on this server!'
  bannerNotFound: '&cThis banner is not found!'
  removeHat:
    name: '&4〉 &cRemove HAT &4〈'
    lore:
      - '&7Click here to remove'
      - '&7banner from Your head!'
  # Name and lore of banner whih is set on player's helmet
  bannerOnHelmet:
    name: '&eHeadBanner'
    useThisLore: true
    lore:
      - '&aThis is one of banner'
      - '&afrom plugin HeadBanner!'
# To add new banner just copy yml structure and change name, giveCommand and lore like You want!
# You can get giveCommand (JSON format) from any minecraft pages to create banners.
# https://www.needcoolshoes.com/banner | http://minecraft.tools/en/banner.php | https://www.planetminecraft.com/banner 
banners:
  banner1:
    name: '&6Banner #1'
    giveCommand: '{BlockEntityTag:{Base:4,Patterns:[{Pattern:bri,Color:15},{Pattern:hhb,Color:4},{Pattern:sc,Color:0},{Pattern:sc,Color:4},{Pattern:bo,Color:0},{Pattern:bo,Color:4}]}}'
    lore:
     - '&7It is super banner!'
  banner2:
    name: '&6Rabbit'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:mc,Color:0},{Pattern:flo,Color:15},{Pattern:tt,Color:12},{Pattern:cr,Color:15},{Pattern:cbo,Color:12},{Pattern:bts,Color:15}]}}'
    lore:
     - '&7It is super banner!'
  someAnother1:
    name: '&6Fox'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:mr,Color:0},{Pattern:cbo,Color:14},{Pattern:mc,Color:14},{Pattern:cre,Color:14},{Pattern:tt,Color:14}]}}'
    lore:
     - '&7It is super banner!'
  someAnother2:
    name: '&6Darkness'
    giveCommand: '{BlockEntityTag:{Base:4,Patterns:[{Pattern:ss,Color:0},{Pattern:cbo,Color:4},{Pattern:tts,Color:0},{Pattern:bts,Color:0},{Pattern:mr,Color:4},{Pattern:bo,Color:0},{Pattern:flo,Color:0},{Pattern:mc,Color:12}]}}'
    lore:
     - '&7It is super banner!'
  someAnother3:
    name: '&6Yin Yang'
    giveCommand: '{BlockEntityTag:{Base:0,Patterns:[{Pattern:rd,Color:15},{Pattern:tl,Color:15},{Pattern:br,Color:0},{Pattern:tts,Color:0},{Pattern:bts,Color:15},{Pattern:ls,Color:0},{Pattern:rs,Color:15}]}}'
    lore:
     - '&7It is super banner!'
  someAnother4:
    name: '&6PokeBall'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:hh,Color:1},{Pattern:mr,Color:0},{Pattern:ts,Color:1},{Pattern:bs,Color:15},{Pattern:ms,Color:0},{Pattern:mc,Color:15}]}}'
    lore:
     - '&7It is super banner!'
  someAnother5:
    name: '&6McPvP'
    giveCommand: '{BlockEntityTag:{Base:4,Patterns:[{Pattern:gra,Color:1},{Pattern:ss,Color:0},{Pattern:cbo,Color:0}]}}'
    lore:
     - '&7It is super banner!'
  someAnother6:
    name: '&6American Flag'
    giveCommand: '{BlockEntityTag:{Base:1,Patterns:[{Pattern:ss,Color:15},{Pattern:tl,Color:4}]}}'
    lore:
     - '&7It is super banner!'
  someAnother7:
    name: '&6Duck'
    giveCommand: '{BlockEntityTag:{Base:0,Patterns:[{Pattern:cs,Color:11},{Pattern:hhb,Color:14},{Pattern:bs,Color:11},{Pattern:bo,Color:11},{Pattern:ms,Color:14},{Pattern:ts,Color:11}]}}'
    lore:
     - '&7It is super banner!'
  someAnother8:
    name: '&6Chicken'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:ts,Color:0},{Pattern:cs,Color:15},{Pattern:ms,Color:14},{Pattern:hhb,Color:1},{Pattern:bo,Color:15},{Pattern:ms,Color:11},{Pattern:bs,Color:15}]}}'
    lore:
     - '&7It is super banner!'
  someAnother9:
    name: '&6Panda'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:flo,Color:0},{Pattern:hhb,Color:15},{Pattern:tts,Color:0},{Pattern:cs,Color:15},{Pattern:cre,Color:0},{Pattern:bs,Color:15}]}}'
    lore:
     - '&7It is super banner!'
  someAnother10:
    name: '&6Rainbow Chain'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:hhb,Color:14},{Pattern:bs,Color:1},{Pattern:hh,Color:10},{Pattern:ms,Color:11},{Pattern:ts,Color:12},{Pattern:bo,Color:0},{Pattern:tts,Color:0},{Pattern:bts,Color:0},{Pattern:bri,Color:0},{Pattern:ss,Color:0}]}}'
    lore:
     - '&7It is super banner!'
  someAnother11:
    name: '&6United Kingdom'
    giveCommand: '{BlockEntityTag:{Base:4,Patterns:[{Pattern:dls,Color:15},{Pattern:drs,Color:15},{Pattern:dls,Color:15},{Pattern:drs,Color:15},{Pattern:cr,Color:1},{Pattern:cs,Color:15},{Pattern:cs,Color:15},{Pattern:ms,Color:15},{Pattern:ms,Color:15},{Pattern:sc,Color:1}]}}'
    lore:
     - '&7It is super banner!'
  someAnother12:
    name: '&6Dragon'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:gru,Color:9},{Pattern:cr,Color:1},{Pattern:mr,Color:0},{Pattern:bo,Color:1},{Pattern:ms,Color:8},{Pattern:cbo,Color:0},{Pattern:sku,Color:0},{Pattern:cre,Color:8},{Pattern:cre,Color:0},{Pattern:flo,Color:0},{Pattern:tt,Color:0},{Pattern:bts,Color:0}]}}'
    lore:
     - '&7It is super banner!'
  someAnother13:
    name: '&6Rice'
    giveCommand: '{BlockEntityTag:{Base:12,Patterns:[{Pattern:dls,Color:3},{Pattern:cr,Color:12},{Pattern:mc,Color:15},{Pattern:hhb,Color:3},{Pattern:cbo,Color:12},{Pattern:bs,Color:12}]}}'
    lore:
     - '&7It is super banner!'
  someAnother14:
    name: '&6MonsterEnergy'
    giveCommand: '{BlockEntityTag:{Base:10,Patterns:[{Pattern:cbo,Color:0},{Pattern:ss,Color:0}]}}'
    lore:
     - '&7It is super banner!'
  someAnother15:
    name: '&6Snake'
    giveCommand: '{BlockEntityTag:{Base:0,Patterns:[{Pattern:cbo,Color:10},{Pattern:rs,Color:0},{Pattern:flo,Color:1},{Pattern:ms,Color:10},{Pattern:tt,Color:0},{Pattern:moj,Color:10}]}}'
    lore:
     - '&7It is super banner!'
  someAnother16:
    name: '&6Nether'
    giveCommand: '{BlockEntityTag:{Base:1,Patterns:[{Pattern:bri,Color:14},{Pattern:ss,Color:0},{Pattern:cbo,Color:0},{Pattern:mr,Color:3},{Pattern:bo,Color:0},{Pattern:flo,Color:0}]}}'
    lore:
     - '&7It is super banner!'
  someAnother17:
    name: '&6Assasins Creed'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:hh,Color:1},{Pattern:mr,Color:15},{Pattern:cbo,Color:1},{Pattern:bs,Color:1},{Pattern:mc,Color:1},{Pattern:bt,Color:1}]}}'
    lore:
     - '&7It is super banner!'
  someAnother18:
    name: '&6Cake'
    giveCommand: '{BlockEntityTag:{Base:1,Patterns:[{Pattern:ss,Color:15},{Pattern:bri,Color:15},{Pattern:hhb,Color:3},{Pattern:ts,Color:0},{Pattern:bs,Color:0},{Pattern:bo,Color:0}]}}'
    lore:
     - '&7It is super banner!'
  someAnother19:
    name: '&6Pikachu'
    giveCommand: '{BlockEntityTag:{Base:4,Patterns:[{Pattern:ss,Color:0},{Pattern:flo,Color:11},{Pattern:sku,Color:1},{Pattern:cr,Color:11},{Pattern:cbo,Color:4},{Pattern:bs,Color:4}]}}'
    lore:
     - '&7It is super banner!'
  someAnother20:
    name: '&6Pikachu'
    giveCommand: '{BlockEntityTag:{Base:4,Patterns:[{Pattern:ss,Color:0},{Pattern:flo,Color:11},{Pattern:sku,Color:1},{Pattern:cr,Color:11},{Pattern:cbo,Color:4},{Pattern:bs,Color:4}]}}'
    lore:
     - '&7It is super banner!'
  someAnother21:
    name: '&6Nether Skull'
    giveCommand: '{BlockEntityTag:{Base:14,Patterns:[{Pattern:sc,Color:0},{Pattern:ts,Color:14},{Pattern:sku,Color:0},{Pattern:gra,Color:1},{Pattern:tts,Color:11},{Pattern:tts,Color:1},{Pattern:bts,Color:11},{Pattern:bts,Color:1}]}}'
    lore:
     - '&7It is super banner!'
  someAnother22:
    name: '&6Suit'
    giveCommand: '{BlockEntityTag:{Base:15,Patterns:[{Pattern:cs,Color:1},{Pattern:lud,Color:0},{Pattern:rd,Color:0},{Pattern:bs,Color:0},{Pattern:hhb,Color:0}]}}'
    lore:
     - '&7It is super banner!'